new PlayerText:hud_modern_info_box[MAX_PLAYERS];
new PlayerText:hud_modern_info_hungrybg[MAX_PLAYERS];
new PlayerText:hud_modern_info_thristbg[MAX_PLAYERS];
new PlayerText:hud_modern_info_hungryicon[MAX_PLAYERS];
new PlayerText:hud_modern_info_thristicon[MAX_PLAYERS];
new PlayerText:hud_modern_info_hungryvalue[MAX_PLAYERS];
new PlayerText:hud_modern_info_thristvalue[MAX_PLAYERS];
new PlayerText:hud_modern_info_hungrypercent[MAX_PLAYERS];
new PlayerText:hud_modern_info_thristpercent[MAX_PLAYERS];

new bool:created_hud_modern_info_td[MAX_PLAYERS];
new bool:showed_hud_modern_info_td[MAX_PLAYERS];