#include <YSI_Coding\y_hooks>

#include "modules\Character\Character_Create\character_create_variables.inc"
#include "modules\Character\Character_Create\character_create_functions.inc"
#include "modules\Character\Character_Create\character_create_callbacks.inc"
#include "modules\Character\Character_Create\character_create_dialogs.inc"
#include "modules\Character\Character_Create\character_create_textdraws.inc"