new player_select_character_actor[MAX_PLAYERS];
new player_select_character_slot[MAX_PLAYERS];

new PlayerText:character_selector_box[MAX_PLAYERS];
new PlayerText:character_selector_header1[MAX_PLAYERS];
new PlayerText:character_selector_header2[MAX_PLAYERS];
new PlayerText:character_selector_infobox[MAX_PLAYERS];
new PlayerText:character_selector_name[MAX_PLAYERS];
new PlayerText:character_selector_level[MAX_PLAYERS];
new PlayerText:character_selector_uang[MAX_PLAYERS];
new PlayerText:character_selector_kelamin[MAX_PLAYERS];
new PlayerText:character_selector_terakhir[MAX_PLAYERS];
new PlayerText:character_selector_terakhirinfo[MAX_PLAYERS];
new PlayerText:character_selector_enterbtn[MAX_PLAYERS];
new PlayerText:character_selector_rightbtn[MAX_PLAYERS];
new PlayerText:character_selector_leftbtn[MAX_PLAYERS];
new PlayerText:character_selector_nochar[MAX_PLAYERS];
new PlayerText:character_selector_indicator[MAX_PLAYERS];