new PlayerText:hud_modern_spdo_box[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carhealth_bg[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carname[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_speed[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_kmh[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carfuel_bg[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carhealth_icon[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carfuel_icon[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carhealth_value[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carfuel_value[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carhealth_cnt[MAX_PLAYERS];
new PlayerText:hud_modern_spdo_carfuel_cnt[MAX_PLAYERS];

new bool:created_hud_modern_speedo_td[MAX_PLAYERS];
new bool:showed_hud_modern_speedo_td[MAX_PLAYERS];