#include <YSI_Coding\y_hooks>

#include "modules\Dynamic\Dealership\DealershipVehicle\dealership_veh_variables.inc"
#include "modules\Dynamic\Dealership\DealershipVehicle\dealership_veh_functions.inc"
#include "modules\Dynamic\Dealership\DealershipVehicle\dealership_veh_callbacks.inc"
#include "modules\Dynamic\Dealership\DealershipVehicle\dealership_veh_dialogs.inc"
#include "modules\Dynamic\Dealership\DealershipVehicle\dealership_veh_commands.inc"