#include <YSI_Coding\y_hooks>

#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_variables.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_functions.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_textdraws.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_callbacks.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_dialogs.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_loadingbar.inc"
#include "modules\System\Vehicle\VehicleMechanics\vehicle_mechanics_commands.inc"